#pragma once

#define KCL_DEVICE_TYPE 0x22
#define IOCTL_KCL_ECHO CTL_CODE(KCL_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_KCL_RESET_STATE CTL_CODE(KCL_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_KCL_SET_MODE CTL_CODE(KCL_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_KCL_SUBMIT_RECORD CTL_CODE(KCL_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

typedef struct _KCL_RECORD_INPUT {
    ULONG DeclaredLength;
    UCHAR Payload[ANYSIZE_ARRAY];
} KCL_RECORD_INPUT, *PKCL_RECORD_INPUT;
